"""
BackchannelEngine — dynamic, human-like "listening" sounds while the USER speaks.

Produces short acknowledgments ("hmm", "yeah", "I see", "go on") that vary
naturally because they are generated by a *separate* tiny LLM call
(gemini-2.5-flash-lite, max 8 tokens) — never a hardcoded list, never the main
turn model, never the conversation history.

Threading model
---------------
* maybe_fire()/note_partial()/reset() are called from the dispatcher and audio
  threads. They are cheap, fully guarded, and NON-blocking: they only update
  shared state (under one lock) and wake the worker.
* The worker is this object's own daemon thread. It owns all the slow work — the
  LLM call (hard-capped by a timeout via a 1-thread executor) and TTS playback —
  so no producer thread is ever blocked.
* All mutable timing/turn state is guarded by self._lock (the Condition's lock).
"""
from __future__ import annotations

import re
import threading
import time
from concurrent.futures import ThreadPoolExecutor, TimeoutError as FuturesTimeout

from assistant import config
from assistant.core.log import get

log = get("backchannel")

_BASE_SYSTEM = (
    "You are a human listener making natural short acknowledgment sounds.\n"
    "Output ONLY 1-3 words maximum. No punctuation. No explanation.\n"
    "Examples of valid outputs: hmm | mhm | yeah | oh | I see | go on | right | "
    "okay | ah | interesting | really | oh wow | sure | mm | uh huh\n"
    "Never output more than 3 words. Never explain. Just the sound/word."
)

_HINTS = {
    "filler": "The user made a thinking sound. Mirror with a soft acknowledgment.",
    "pause": "The user paused. Encourage them to continue.",
    "length_15": "The user is telling you something. Show you are following along.",
    "length_30": "The user has been speaking a while. Show active listening.",
    "active_listening": "The user has been speaking for a long time. Briefly let them "
                        "know you are listening, e.g. 'go on' or 'I am listening, sir'.",
}


def _hint_for(trigger: str, emotion: str | None) -> str:
    hint = _HINTS.get(trigger, "")
    if emotion == "excited":
        hint += " The user sounds excited."
    elif emotion in ("empathetic", "sad"):
        hint += " The user sounds sad or troubled. Be gentle."
    return hint.strip()


def _sanitize(text: str) -> str:
    """Force the model output into a clean 1-3 word listening sound."""
    if not text:
        return ""
    first = text.strip().splitlines()[0] if text.strip() else ""
    cleaned = re.sub(r"[^A-Za-z' ]", "", first).strip()
    words = cleaned.split()
    if not words:
        return ""
    return " ".join(words[:3]).lower()


class _BackchannelLLM:
    """Thin wrapper over the fast model. Best-effort: any failure → '' (skip).

    Deliberately has NO fallback word list — per spec, variation must come from
    the model, not random.choice.
    """

    def __init__(self):
        from google import genai
        self._genai = genai
        try:
            from google.genai import types
            self._types = types
        except Exception:
            self._types = None
        self._client = genai.Client(api_key=config.GOOGLE_API_KEY)
        self.model = config.BACKCHANNEL_MODEL

    def listen_sound(self, partial_text: str, hint: str) -> str:
        system = _BASE_SYSTEM + (f"\nContext: {hint}" if hint else "")
        contents = partial_text.strip() or "(the user is speaking)"
        if self._types is not None:
            cfg = self._types.GenerateContentConfig(
                system_instruction=system,
                max_output_tokens=8,
                temperature=1.0,
                candidate_count=1,
            )
            resp = self._client.models.generate_content(
                model=self.model, contents=contents, config=cfg,
            )
        else:  # older SDK: fold the system prompt into the content
            resp = self._client.models.generate_content(
                model=self.model, contents=f"{system}\n\nUser so far: {contents}",
            )
        return _sanitize(getattr(resp, "text", "") or "")


class BackchannelEngine(threading.Thread):
    def __init__(self, bus, tts_service):
        super().__init__(name="Backchannel", daemon=True)
        self.bus = bus
        self.tts = tts_service
        self._llm: _BackchannelLLM | None = None
        self._executor = ThreadPoolExecutor(max_workers=1, thread_name_prefix="BC-LLM")

        # ---- timing / per-utterance state (ALL guarded by self._lock) -------
        self._lock = threading.Lock()
        self._cond = threading.Condition(self._lock)
        self._pending: tuple[str, str, str | None] | None = None  # (text, trigger, emotion)
        self._last_fire = 0.0
        self._count_this_turn = 0
        self._length_fired: set[int] = set()
        self._current_utt_id: str | None = None
        self._last_partial_text = ""
        self._suspended = False   # True after Jarvis starts responding, until next utterance

        # Tunables (spec defaults, overridable via config/.env).
        self.MIN_BETWEEN = config.BACKCHANNEL_MIN_GAP_S
        self.MIN_WORDS = config.BACKCHANNEL_MIN_WORDS
        self.MAX_PER_TURN = config.BACKCHANNEL_MAX_PER_TURN
        self.LLM_TIMEOUT = config.BACKCHANNEL_LLM_TIMEOUT_S

    # ===================================================================
    # Producer-side API (dispatcher / audio threads) — cheap & non-blocking
    # ===================================================================
    def note_partial(self, text: str, utterance_id: str | None):
        """Record the latest partial so a text-less 'pause' trigger has length."""
        if not config.ENABLE_BACKCHANNEL or not text:
            return
        with self._lock:
            self._roll_utterance(utterance_id)
            self._last_partial_text = text

    def maybe_fire(self, partial_text: str, trigger: str,
                   utterance_id: str | None = None, emotion: str | None = None):
        """Decide (cheaply) whether to schedule a backchannel; never blocks.

        Returns immediately after updating guarded state + waking the worker.
        """
        if not config.ENABLE_BACKCHANNEL:
            return
        now = time.monotonic()
        with self._lock:
            self._roll_utterance(utterance_id)

            text = partial_text.strip() if partial_text else self._last_partial_text
            if partial_text and partial_text.strip():
                self._last_partial_text = partial_text.strip()

            # ---- hard guards -------------------------------------------------
            if self._suspended:
                return                                  # Jarvis already responding this turn
            if self.bus.state.speaking:
                return                                  # real response is playing
            if now - self._last_fire < self.MIN_BETWEEN:
                return                                  # too soon since last sound
            if self._count_this_turn >= self.MAX_PER_TURN:
                return                                  # per-utterance cap reached
            if self.bus.stt_in_q.qsize() > 2:
                return                                  # STT backlogged — stay quiet

            words = len(text.split())

            # ---- per-trigger admission --------------------------------------
            if trigger == "length_15":
                if words < 15 or 15 in self._length_fired:
                    return
                self._length_fired.add(15)
            elif trigger == "length_30":
                if words < 30 or 30 in self._length_fired:
                    return
                self._length_fired.add(30)
            elif trigger == "pause":
                if words < self.MIN_WORDS:
                    return                              # ignore tiny fragments
            elif trigger in ("filler", "active_listening"):
                pass                                    # may carry no/long text
            else:
                return                                  # unknown trigger

            # Reserve the slot now so two threads can't double-fire.
            self._last_fire = now
            self._count_this_turn += 1
            self._pending = (text, trigger, emotion or self.bus.state.emotion)
            self._cond.notify()

    def reset(self):
        """Called when Jarvis starts responding — stop & disarm until the next
        user utterance begins (a new utterance_id lifts the suspension)."""
        with self._lock:
            self._count_this_turn = 0
            self._length_fired.clear()
            self._pending = None
            self._suspended = True

    # ---- internal (must hold self._lock) ----------------------------------
    def _roll_utterance(self, utterance_id: str | None):
        if utterance_id and utterance_id != self._current_utt_id:
            self._current_utt_id = utterance_id
            self._count_this_turn = 0
            self._length_fired.clear()
            self._last_partial_text = ""
            self._suspended = False          # fresh user utterance → re-arm

    def _undo_slot(self):
        with self._lock:
            if self._count_this_turn > 0:
                self._count_this_turn -= 1

    # ===================================================================
    # Worker thread — owns the slow LLM call + playback
    # ===================================================================
    def run(self):
        if not config.ENABLE_BACKCHANNEL:
            return
        try:
            self._llm = _BackchannelLLM()
        except Exception:
            log.info("backchannel LLM unavailable; backchannels disabled", exc_info=True)
            return
        log.info("backchannel ready (model=%s)", config.BACKCHANNEL_MODEL)

        while not self.bus.shutdown.is_set():
            # Whole-iteration guard: a backchannel is a non-essential nicety, so
            # ANY error here must be swallowed and the worker kept alive.
            try:
                with self._cond:
                    if self._pending is None:
                        self._cond.wait(timeout=0.3)
                    req, self._pending = self._pending, None
                if req is None:
                    continue
                partial_text, trigger, emotion = req

                if self.bus.state.speaking:          # response started while queued
                    self._undo_slot()
                    continue

                sound = self._call_llm(partial_text, _hint_for(trigger, emotion))
                if not sound:
                    self._undo_slot()                # don't waste the per-turn budget
                    continue
                if self.bus.state.speaking:          # final guard right before audio
                    self._undo_slot()
                    continue

                try:
                    self.tts.speak_backchannel(sound)
                    log.info("[BACKCHANNEL] trigger=%s emotion=%s sound=%r", trigger, emotion, sound)
                except Exception:
                    log.debug("backchannel playback failed", exc_info=True)
            except Exception:
                log.exception("backchannel loop error — worker stays alive")
                time.sleep(0.1)

    def _call_llm(self, partial_text: str, hint: str) -> str:
        """Run the mini-LLM with a hard timeout; on slow/error → '' (skip)."""
        try:
            fut = self._executor.submit(self._llm.listen_sound, partial_text, hint)
            return fut.result(timeout=self.LLM_TIMEOUT)
        except FuturesTimeout:
            log.debug("backchannel LLM > %.2fs — skipped", self.LLM_TIMEOUT)
            return ""
        except Exception:
            log.debug("backchannel LLM error — skipped", exc_info=True)
            return ""
